In [1]:
import pandas as pd

In [2]:
URL = r"C:\Users\natasha\Downloads\earthchem_download_62420.xlsx"

In [3]:
Sample_id = pd.read_excel(URL, header = None)

In [4]:
#Sample_id = Sample_id.reset_index(drop=True, inplace=True)

In [5]:
Sample_id[:10]

,0,1,2,3,4,5,6,7,8,9,...,88,89,90,91,92,93,94,95,96,97
0,"EarthChem Download: Friday, Jul. 17, 2020 6:27...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Search Criteria:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Materials,Igneous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,SAMPLE ID,IGSN,SOURCE,DOI,TITLE,JOURNAL,AUTHOR,EXPEDITION ID,LATITUDE,LONGITUDE,...,DY,HO,ER,TM,YB,LU,H2O_M,H2O_P,H2O_M,H2O_P
6,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,4.16,NaN,NaN,NaN,1.67,0.23,NaN,NaN,NaN,NaN
9,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
Sample_id = Sample_id.drop([0,1,2,3,4])

In [7]:
Sample_id.head()

,0,1,2,3,4,5,6,7,8,9,...,88,89,90,91,92,93,94,95,96,97
5,SAMPLE ID,IGSN,SOURCE,DOI,TITLE,JOURNAL,AUTHOR,EXPEDITION ID,LATITUDE,LONGITUDE,...,DY,HO,ER,TM,YB,LU,H2O_M,H2O_P,H2O_M,H2O_P
6,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,4.16,NaN,NaN,NaN,1.67,0.23,NaN,NaN,NaN,NaN
9,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Specimen_id = Specimen_id.rename(columns=Specimen_id.iloc[0]).drop(Specimen_id.index[0])
Sample_id = Sample_id.reset_index(drop = True)

In [10]:
Sample_id.head()

,0,1,2,3,4,5,6,7,8,9,...,88,89,90,91,92,93,94,95,96,97
0,SAMPLE ID,IGSN,SOURCE,DOI,TITLE,JOURNAL,AUTHOR,EXPEDITION ID,LATITUDE,LONGITUDE,...,DY,HO,ER,TM,YB,LU,H2O_M,H2O_P,H2O_M,H2O_P
1,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,4.16,NaN,NaN,NaN,1.67,0.23,NaN,NaN,NaN,NaN
4,KAK19XX-006-007F,NaN,EARTHCHEMDB,10.1016/S0024-4937(87)80005-1,PETROLOGY AND GEOCHRONOLOGY OF VOLCANIC ROCKS ...,LITHOS,"GARCIA, M O; GROOMS, D G; NAUGHTON, J J",KAK19XX,25.6833,-167.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN